### ISSUE TITLE
DevOps/CIBox codesprint, Aug 8, 20015

### ISSUE THREAD

**Issue by podarok** [propeoplemd/cibox#207]
Docs
===
**#209 CIBox naming convention**
**#190 Create how-to about integrate CIBox to new team/company**
**#191 HOW-to sell CIBox**
#238 GitHub webhooks documentation and examples
#206 Create CIBox/DevOps mailing list

Junior
===
**#230 PHP 5.6 regression**
**#231 Reinstall.yml: move settings.php to variables**
#14 Change projectUrl for github project for all jobs to be copied to jenkins CI server
#70 Add htpasswd protection to /backup and /cache folders
#73 Add default permissions set for a CI server host
#84 proper install for jshint
#95 Add environment variable

Middle
===
**#223 [Important] ghprb plugin has a bug**
**#235 Clear memcache on Acquia before updates and registry_rebuild**
**#237 "Append portion of build log" disappears after save**
#9 Add http://www.sonarqube.org/ integration to jenkins
#36 Add array of rules to skip for php codesniffer
#39 Drupal 8 support
#44 cs fixer
#56 All buffers optimization for CI server
#57 All caches optimization
#58 All limits optimization
#82 Install mailcatcher to both VM and CI server
#93 Security vulnerabilities scanning
#189 Initial sniffers/linters counter
#210 Add varnish for CI server and Vagrantbox
#213 Universal initial behat test for CT field specification
#217 Integrate import frameworks into cibox
#221 GULP workflow

Senior
===
**#236 Acquia integration**
#7 Change opcache to xcache for CI builds for speedup
#23 fstab optimizations
#33 Redis instead memcache
#35 apache alongside nginx
#51 Create CI buillds for cibox repo
#53 Install munin monitoring
#74 Every build should have it's own subdomain
#76 migrate to file_per_table - add role for that
#98 Add fakeswap.sh script for OpenVZ powered VPSes

**Comment by M1r1k** [comment]
I want to reuse as much as possible from https://github.com/geerlingguy/drupal-vm

**Comment by vladdancer** [comment]
I would recomend https://github.com/spencergibb/battleschool as a base to build local dev environment. The main idea is to aggregate playbooks from anyware (git, galaxy, ftp, cloud ...). Also there is https://github.com/protobox/protobox for web based ansible config.

Thanks for drupal-vm link.

**Comment by Sanchiz** [comment]
My issues for the sprint:
https://github.com/propeoplemd/cibox/issues?q=is%3Aopen+is%3Aissue+assignee%3ASanchiz+milestone%3A%22%231+DevOps%2FCIBox+codesprint+Ukraine+2015%22
