### ISSUE TITLE
[Important] ghprb plugin has a bug

### ISSUE THREAD

**Issue by podarok** [propeoplemd/cibox#223]
GitHub PR Builder plugin has got a bug https://github.com/jenkinsci/ghprb-plugin/issues/134
Please, use ghprb 1.24.4 from here http://updates.jenkins-ci.org/download/plugins/ghprb/1.24.4/ghprb.hpi untill https://github.com/jenkinsci/ghprb-plugin/issues/134 fixed

**Comment by Sanchiz** [comment]
Also new version doesn't show:
- "Comment file" in Job settings
- "Lines of build log to include in comments" in general settings
- "Published Jenkins URL" in general settings

When you build CI server from scratch, GitHub PR Builder post empty messages to GitHub when build is failed.

**Comment by Sanchiz** [comment]
How to solve issue with comments in newer versions(not in all) https://github.com/janinko/ghprb/issues/292#issuecomment-115257608

**Comment by podarok** [comment]
@Sanchiz can we update ghprb plugin then?

**Comment by Sanchiz** [comment]
@podarok no, it's still not stable https://github.com/janinko/ghprb/issues/292#issuecomment-165712647

**Comment by podarok** [comment]
ah, ok, waiting then

**Comment by Sanchiz** [comment]
Here's issue for Jenkins plugin https://github.com/janinko/ghprb/issues/379

**Comment by Sanchiz** [comment]
How to fix not available "Comment file" and "Append portion of build log" field in Global/Job Configuration.

Add this code into `<extensions>` section in configuration file:
```
<org.jenkinsci.plugins.ghprb.extensions.comments.GhprbCommentFile>
  <commentFilePath>${WORKSPACE}/commentinfo.md</commentFilePath>
</org.jenkinsci.plugins.ghprb.extensions.comments.GhprbCommentFile>
<org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildLog>
  <logExcerptLines>25</logExcerptLines>
</org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildLog>
```

For Global Configuration use `/var/lib/jenkins/org.jenkinsci.plugins.ghprb.GhprbTrigger.xml` file and for Job configuration `/var/lib/jenkins/jobs/JOB_NAME/config.xml`.
