### ISSUE TITLE
Reinstall.yml: move settings.php to variables

### ISSUE THREAD

**Issue by Sanchiz** [propeoplemd/cibox#231]

**Comment by podarok** [comment]
this one looks like was done by your refactoring some time ago, right? @Sanchiz

**Comment by Sanchiz** [comment]
Not yet. settings.php is still hardcoded in script.

**Comment by Sanchiz** [comment]
We should move this to variable 
https://github.com/propeoplemd/cibox/blob/master/github/files/drupal7/scripts/devops/reinstall/post_settings.yml#L9

**Comment by podarok** [comment]
ah, ok, was wondered becuase of lack of summary info here
