### ISSUE TITLE
"Append portion of build log" disappears after save

### ISSUE THREAD

**Issue by Sanchiz** [propeoplemd/cibox#237]
Manage Jenkins > Configure System > GitHub Pull Request Builder

GitHub PR builder settings "Append portion of build log" disappears after save
https://goo.gl/AMDhO7

**Comment by podarok** [comment]
Right now this is fixed for 1.0.0

I guess we should find ghprb plugin version without this issue and update it's config to meet new version.
This can be done as minor change like 1.0.1 if there is a simple solution. 
For now marked it as non important change
