### ISSUE TITLE
META: Remove redundant code (Local development VM)

### ISSUE THREAD

**Issue by danylevskyi** [propeoplemd/cibox#264]
As I noticed the code of local development VM (whiting `github` directory) has a lot of redundancies from previous provisioning tools like `puphpet`. I think that redundant code prevents new users from understanding the system as a whole.

I propose to use this issue to collect redundancies. Each of the issues should be confirmed by lead developer (@podarok). After that new developers (like me :) we'll have opportunity to learn the system by improving it.

- [x] #263 - fixed.
- [x] #265 - pull request.
- [x] #266 - fixed.
- [x] #267 - fixed.
- [x] #270 - pull request.

**Comment by podarok** [comment]
confirmed

**Comment by danylevskyi** [comment]
It seems `ssh-keygen.sh` is not used at all for dev box provisioning. Adding new issue to META.

**Comment by podarok** [comment]
@danylevskyi yes, It is not used anymore, we've switched to password protected autentification and got used to it because of convenience

**Comment by danylevskyi** [comment]
As it appeared some of the merges didn't worked. For example, #270 is merged, but file still exists. I think, it's due to complex directory changes. So, I'll open new issues and prepare new pull requests.

**Comment by danylevskyi** [comment]
@podarok, please check pull requests for #265 and #270.
