### ISSUE TITLE
Remove execute-files.sh

### ISSUE THREAD

**Issue by danylevskyi** [propeoplemd/cibox#266]
Puphpet uses a technique of running special scripts at the end of provisioning. I trully believe there are better ways to organize provisioning.

I propose to remove `execute-files.sh` logic.

**Comment by podarok** [comment]
confirmed

**Comment by danylevskyi** [comment]
Closed with #268

**Comment by danylevskyi** [comment]
Directories: `github/files/vagrant/puppet/puphpet/files/exec-always` and `github/files/vagrant/puppet/puphpet/files/exec-once` also should be removed.
