### ISSUE TITLE
"mount.nfs: Connection timed out"

### ISSUE THREAD

**Issue by valentine94** [propeoplemd/cibox#300]
This caused if UncomplicatedFirewall(Ubuntu 14.04) has Incoming Policy - Deny option(default settings).
![screenshot from 2015-11-04 11 43 37](https://cloud.githubusercontent.com/assets/5767874/10934676/ecbd51e2-82e9-11e5-9986-1980bc9db18b.png)

**Comment by podarok** [comment]
@valentine94 can you please provide a fast how-to fix it? We will add it to our WiKi

**Comment by valentine94** [comment]
@podarok sure, here is a global allowing/denying commands.
For allowing all:
```sh
sudo ufw default allow incoming && sudo ufw reload
```
For deny all:
```sh
sudo ufw default deny incoming && sudo ufw reload
```

It's also has some advanced options, which described here -> https://www.digitalocean.com/community/tutorials/how-to-setup-a-firewall-with-ufw-on-an-ubuntu-and-debian-cloud-server

**Comment by podarok** [comment]
Thanks a lot
added to wiki
https://github.com/propeoplemd/cibox/issues/300
