### ISSUE TITLE
mount.nfs Connection timed out

### ISSUE THREAD

**Issue by DmitryDrozdik** [propeoplemd/cibox#302]
I had an issue with mounting shared folders. Here is a screenshot https://gyazo.com/ee608122315f8211ff62f023b8ab55de

![image](https://cloud.githubusercontent.com/assets/563412/11121549/302f5486-895f-11e5-8a0b-65392ef04a43.png)

This issue has been fixed by cleaning /etc/exports and restarting nfs kernel server. 

Please add this information to the wiki as a way of fixing this issue. 

Thanks.

**Comment by podarok** [comment]
added to wiki. Thank you
