### ISSUE TITLE
Remove redundant host_vars

### ISSUE THREAD

**Issue by danylevskyi** [propeoplemd/cibox#309]
Currently we have 2 redundant host_vars files in the project root.

```
dmytro@DZ77GA-70K:~/Projects/cibox$ tree host_vars/
host_vars/
├── 104.131.20.201
└── 178.62.153.157
```

I propose to remove them and add README.md file with the link to Ansible documentation.
http://docs.ansible.com/ansible/intro_inventory.html#host-variables

**Comment by podarok** [comment]
Yup. This is abandoned code from about 1.5 year version ago.
Work on this when you have a time
