### ISSUE TITLE
github.yml crashes because of wrong version of Drupal

### ISSUE THREAD

**Issue by danylevskyi** [propeoplemd/cibox#311]
The new Drupal is came out and this code is not valid now:

```
  - name: Downloading drupal to {{ drupal_subfolder }} subfolder
    shell: "cd {{ repo_subfolder }} && drush -y --drupal-project-rename={{ drupal_subfolder }} dl drupal"
    when: drupal_stat.changed == True
    register: drupal_dl
```

Later steps are crashed.
Need to specify Drupal version here.

**Comment by podarok** [comment]
This leads to architecture change. I'm guessing that for now drush trying to download D8
So we need to use drupal_version variable here since today

**Comment by Sanchiz** [comment]
@podarok already merged PR https://github.com/propeoplemd/cibox/pull/312

**Comment by podarok** [comment]
cool, thanks
