### ISSUE TITLE
Host and placeholders

### ISSUE THREAD

**Issue by Sanchiz** [propeoplemd/cibox#326]
We should get rid of placeholders `CHANGE_ME` in jenkinsbox.yml. Those settings should be provided in separate .yml file, e.g. `config.yml`. Also host IP should be provided in config.yml.

**Comment by podarok** [comment]
@danylevskyi check ability to include cibox.cfg from ansible.cfg

**Comment by Sanchiz** [comment]
We should also pass into playbook variable `jenkins_server_ip` that should be equals to `host ip`.
