### ISSUE TITLE
Installation/run instructions needed

### ISSUE THREAD

**Issue by CharlesBelov** [propeoplemd/cibox#428]
I can't find any instructions on how to install and run this for day-to-day use. Please add them and/or point me to them.

**Comment by podarok** [comment]
https://github.com/propeoplemd/cibox/blob/master/docs/Quickstart.md

**Comment by podarok** [comment]
@CharlesBelov shoot us with additional questions if there are any.
Also you can have a look at sessions about a project here http://docs.cibox.tools/en/latest/about/Videos-presentations/
